unit MSNPConstants;

interface

const
  CRLF = #13#10;
  MSNServerHost = 'messenger.hotmail.com';
  MSNServerPort = 1863;
  MaxMSNMessageLength = 1664;
  LCID = '1043';

const
  SYNTAX_ERROR = 200;
  INVALID_PARAMETER = 201;
  INVALID_USER = 205;
  DOMAIN_NAME_MISSING = 206;
  ALREADY_LOGGED_IN = 207;
  INVALID_USERNAME = 208;
  INVALID_FUSERNAME = 209;
  USER_LIST_FULL = 210;
  USER_ALREADY_THERE = 215;
  USER_ALREADY_ON_LIST = 216;
  USER_NOT_ONLINE = 217;
  ALREADY_IN_MODE = 218;
  USER_IS_IN_OPPOSITE_LIST = 219;
  TOO_MANY_GROUPS = 223;
  INVALID_GROUP_1 = 224;
  PRINCIPAL_NOT_IN_GROUP = 225;
  GROUP_NAME_TOO_LONG = 229;
  CANNOT_REMOVE_GROUP_ZERO = 230;
  INVALID_GROUP_2 = 231;
  SWITCHBOARD_FAILED = 280;
  TRANSFER_TO_SWITCHBOARD_FAILED = 281;

  PARAMETER_MISSING = 300;
  NOT_LOGGED_IN = 302;

  INTERNAL_SERVER_ERROR = 500;
  DATABASE_SERVER_ERROR = 501;
  COMMAND_DISABLED = 502;
  FILE_OPERATION_FAILED = 510;
  MEMORY_ALLOCATION_FAILED = 520;
  CHALLENGE_RESPONSE_FAILED = 540;

  SERVER_IS_BUSY = 600;
  SERVER_IS_UNAVALIABLE = 601;
  PEER_NAMESERVER_IS_DOWN = 602;
  DATABASE_CONNECTION_FAILED = 603;
  SERVER_IS_GOING_DOWN = 604;
  SERVER_UNAVALIABLE = 605;

  COULD_NOT_CREATE_CONNECTION  = 707;
  BAD_CVR_PARAMETERS = 710;
  WRITE_IS_BLOCKING  = 711;
  SESSION_IS_OVERLOADED = 712;
  CALLING_TOO_RAPIDLY = 713;
  TOO_MANY_SESSIONS  = 714;
  NOT_EXPECTED = 715;
  BAD_FRIEND_FILE = 717;
  NOT_EXPECTED_CVR = 731;

  CHANGING_TOO_RAPIDLY = 800;

  SERVER_TOO_BUSY_1 = 910;
  AUTHENTICATION_FAILED = 911;
  SERVER_TOO_BUSY_2 = 912;
  NOT_ALLOWED_WHEN_HIDING = 913;
  NOT_ACCEPTING_NEW_USERS = 920;
  SERVER_TOO_BUSY_3 = 921;
  SERVER_TOO_BUSY_4 = 922;
  KIDS_PASSPORT_WITHOUT_PARENTAL_CONSENT = 923;
  PASSPORT_ACCOUNT_NOT_YET_VERIFIED = 924;
  BAD_TICKET = 928;

implementation

end.
